name: demographics
channels:
    - conda-forge
dependencies:
    - python=3.6
    - notebook
    - numpy=1.13.3
    - matplotlib=2.1.0
    - pandas=0.20.3
    - seaborn=0.8.0
    - PyTables=3.4.2
    - ghp-import
    - sphinx>=1.5
    - sphinx_rtd_theme
    - pip:
      - recommonmark==0.4.0