name: demographics
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - notebook
    - numpy=1.13.3
    - matplotlib=2.1.0
    - pandas=0.20.3
    - seaborn=0.8.0
    - PyTables=3.4.2
    - ghp-import=0.5.5  
       
    - pip:
      - nbsphinx==0.2.17
      - recommonmark==0.4.0